nelmio_api_doc:
    documentation:
        info:
            title: API BileMo
            description: This is the documentation for the API BileMo
            version: 1.0.0
    #areas: # to filter documented areas
        #path_patterns:
            #- ^/(?!api/doc$) # Accepts routes under / except /doc
        #host_patterns: 
            #- ^/
